[project]
name = "ifeanyichukwu-etl-pipeline"
version = "0.1.0"
description = "API Based ETL Pipeline with Polars, PostgreSQL, IMDB via RapidAPI"
authors = [
    {name = "ioaviator",email = "kingsolomonifeanyi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars (>=1.25.2,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "sqlalchemy (>=2.0.39,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = "^8.3.5"

